### PR TITLE
Fix: Input param type Contract[] 

### PR DESCRIPTION
**Pull request by stevennevins**
I used this as a fix in my local project

### CODE REVIEW

**Comment by stevennevins** [comment]
partially addresses https://github.com/pbshgthm/blacksmith/issues/4

**Comment by pbshgthm** [comment]
Good find! Thanks for the pr, looks good to me. Will merge tomorrow. 

Would also love to have a look at your project and how you are using it, if possible. I could possibly add it to the docs as an example if it's open-source.

**Comment by stevennevins** [comment]
I did a bit more investigating, and I think the second piece https://github.com/pbshgthm/blacksmith/issues/4 was an issue.  I used the above commit to resolve it in my project to format the return statement to market the target as payable

**Comment by stevennevins** [comment]
@pbshgthm probably can't share the repo for a while but will follow up once it's public!

**Comment by pbshgthm** [comment]
Nice work with the receive function. Will test things out in the evening and merge. Thanks!

**Review by pbshgthm — APPROVED** [review]

**Review by pbshgthm — APPROVED** [review]

**Comment by pbshgthm** [comment]
Hi @stevennevins, till commit [dbf9d11](https://github.com/pbshgthm/blacksmith/pull/5/commits/dbf9d11cb705475621a9e5e7547acc84321820b1) everything looks good. I'm having a little trouble understanding [07b1efb](https://github.com/pbshgthm/blacksmith/pull/5/commits/07b1efb210f8e38be2ed295c9d135bc4109cd4d8). Can you help clarify it?

**Comment by stevennevins** [comment]
Hi @pbshgthm made an example here https://github.com/stevennevins/blacksmith/tree/demo-payable

**Comment by stevennevins** [comment]
Ahh I see what's happening now, it's the prb-proxy target as a function param being used instead of the target variable in the contract, so not an issue with the codegen.  Sorry for the confusion! 😅

**Comment by pbshgthm** [comment]
No issues! Thanks for the rest of the fixes. Looks fine to me so merging them.

**Pull request merged**
